CREATE TABLE invoices (
    uuid VARCHAR(255) NOT NULL,
    nr TEXT,
    from_name TEXT,
    from_company_name TEXT,
    from_company_address TEXT,
    from_company_extra TEXT,
    to_name TEXT,
    to_company_name TEXT,
    to_company_address TEXT,
    to_company_extra TEXT,
    items TEXT,
    due_date TEXT,
    date_issued TEXT,
    qty_type TEXT,
    currency TEXT,
    payment_details TEXT,
    discount_name TEXT,
    discount_percentage TEXT,
    tax_type TEXT,
    tax_name TEXT,
    tax_percentage TEXT);
